version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: bazel
    directory: "/"
    schedule:
      interval: weekly
    groups:
      bazel-modules:
        patterns: ["*"]
