name: Mindclade repository metadata

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  validate:
    uses: mindclade/.github/.github/workflows/reusable-metadata-validation.yml@8d3059d5e14e5f7af861ad190e329fa4dac27dfc
    with:
      source_revision: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha || github.sha }}
