name: Mindclade repository metadata

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  validate:
    uses: mindclade/.github/.github/workflows/reusable-metadata-validation.yml@c097ef86c25991a400050c13e78574e8d3d8c071
    with:
      source_revision: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha || github.sha }}
