name: Mindclade repository metadata

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  validate:
    uses: mindclade/.github/.github/workflows/reusable-metadata-validation.yml@defb8afbaac17ed6bb9d3959d185ec9000bd2184
    with:
      source_revision: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha || github.sha }}
